/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./App.{js,jsx,ts,tsx}",
    "./app/**/*.{js,jsx,ts,tsx}",
    "./src/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        background: "#131314",
        surface: {
          DEFAULT: "#131314",
          dim: "#131314",
          bright: "#3a393a",
          lowest: "#0e0e0f",
          low: "#1c1b1c",
          container: "#201f20",
          high: "#2a2a2b",
          highest: "#353436",
        },
        "on-surface": "#e5e2e3",
        "on-surface-variant": "#cbc3d7",
        "inverse-surface": "#e5e2e3",
        "inverse-on-surface": "#313031",
        outline: "#958ea0",
        "outline-variant": "#494454",
        "surface-tint": "#d0bcff",
        primary: {
          DEFAULT: "#d0bcff",
          container: "#a078ff",
          fixed: "#e9ddff",
          "fixed-dim": "#d0bcff",
        },
        "on-primary": "#3c0091",
        "on-primary-fixed": "#23005c",
        "on-primary-fixed-variant": "#5516be",
        "inverse-primary": "#6d3bd7",
        secondary: {
          DEFAULT: "#4cd7f6",
          container: "#03b5d3",
          fixed: "#acedff",
          "fixed-dim": "#4cd7f6",
        },
        "on-secondary": "#003640",
        "on-secondary-fixed": "#001f26",
        "on-secondary-fixed-variant": "#004e5c",
        tertiary: {
          DEFAULT: "#ffb869",
          container: "#ca801e",
          fixed: "#ffdcbb",
          "fixed-dim": "#ffb869",
        },
        "on-tertiary": "#482900",
        "on-tertiary-fixed": "#2c1700",
        "on-tertiary-fixed-variant": "#673d00",
        error: {
          DEFAULT: "#ffb4ab",
          container: "#93000a",
        },
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
        difficulty: {
          easy: "#22c55e",
          medium: "#eab308",
          hard: "#ef4444",
          "no-rank": "#958ea0",
        },
      },
      fontFamily: {
        sans: ["Inter", "System"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.04em", fontWeight: "800" }],
        "display-md": ["36px", { lineHeight: "44px", letterSpacing: "-0.03em", fontWeight: "800" }],
        "headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "title-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.08em", fontWeight: "700" }],
      },
      borderRadius: {
        sm: "4px",
        DEFAULT: "8px",
        md: "12px",
        lg: "16px",
        xl: "24px",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "40px",
      },
    },
  },
  plugins: [],
};
