const { palette } = require("./src/theme/palette");

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./App.{js,jsx,ts,tsx}",
    "./app/**/*.{js,jsx,ts,tsx}",
    "./src/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        // Brand palette (light lavender -> vibrant purple -> deep purple-black).
        color1: palette.color1,
        color2: palette.color2,
        color3: palette.color3,
        color4: palette.color4,
        color5: palette.color5,
        color6: palette.color6,
        color7: palette.color7,
        background: palette.color7,
        surface: {
          DEFAULT: palette.color7,
          dim: palette.color7,
          bright: palette.color4,
          lowest: palette.color7,
          low: palette.color6,
          container: palette.color6,
          high: palette.color5,
          highest: palette.color5,
        },
        "on-surface": palette.color1,
        "on-surface-variant": palette.color2,
        "inverse-surface": "#e5e2e3",
        "inverse-on-surface": "#313031",
        outline: palette.color5,
        "outline-variant": palette.color6,
        "surface-tint": palette.color3,
        primary: {
          DEFAULT: palette.color4,
          container: palette.color5,
          fixed: palette.color1,
          "fixed-dim": palette.color2,
        },
        "on-primary": palette.color1,
        "on-primary-fixed": palette.color7,
        "on-primary-fixed-variant": palette.color5,
        "inverse-primary": palette.color5,
        secondary: {
          DEFAULT: palette.color3,
          container: palette.color5,
          fixed: palette.color1,
          "fixed-dim": palette.color2,
        },
        "on-secondary": palette.color7,
        "on-secondary-fixed": palette.color7,
        "on-secondary-fixed-variant": palette.color6,
        tertiary: {
          DEFAULT: "#ffb869",
          container: "#ca801e",
          fixed: "#ffdcbb",
          "fixed-dim": "#ffb869",
        },
        "on-tertiary": "#482900",
        "on-tertiary-fixed": "#2c1700",
        "on-tertiary-fixed-variant": "#673d00",
        error: {
          DEFAULT: "#ffb4ab",
          container: "#93000a",
        },
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
        difficulty: {
          easy: "#22c55e",
          medium: "#eab308",
          hard: "#ef4444",
          "no-rank": "#958ea0",
        },
      },
      fontFamily: {
        sans: ["OpenSans_400Regular", "System"],
      },
      // Letter-spacing removed app-wide: every tracking-* utility resolves to 0.
      letterSpacing: {
        tighter: "0px",
        tight: "0px",
        normal: "0px",
        wide: "0px",
        wider: "0px",
        widest: "0px",
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", fontWeight: "800" }],
        "display-md": ["36px", { lineHeight: "44px", fontWeight: "800" }],
        "headline-lg": ["28px", { lineHeight: "36px", fontWeight: "700" }],
        "headline-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "title-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "700" }],
      },
      borderRadius: {
        sm: "4px",
        DEFAULT: "8px",
        md: "12px",
        lg: "16px",
        xl: "24px",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "40px",
      },
    },
  },
  plugins: [],
};
